# Generated by Django 3.0.5 on 2020-05-24 10:19

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Email', models.CharField(default=None, max_length=100)),
                ('Phone', models.CharField(default=None, max_length=100)),
                ('gender', models.CharField(default=None, max_length=100)),
                (
                    'person',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='app.Person'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Email', models.CharField(default=None, max_length=100)),
                ('Phone', models.CharField(default=None, max_length=100)),
                ('gender', models.CharField(default=None, max_length=100)),
                (
                    'person',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='app.Person'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('Speciality', models.CharField(default=None, max_length=100)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Email', models.CharField(default=None, max_length=100)),
                ('Phone', models.CharField(default=None, max_length=100)),
                ('gender', models.CharField(default=None, max_length=100)),
                (
                    'person',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='app.Person'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'Date',
                    models.DateField(default=datetime.date.today, verbose_name='Date'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PD', 'Pending'),
                            ('AP', 'Approved'),
                            ('RJ', 'rejected'),
                        ],
                        default='PD',
                        max_length=2,
                    ),
                ),
                (
                    'message',
                    models.CharField(default='Pending Approval', max_length=1000),
                ),
                (
                    'Doctor',
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='app.Doctor',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
