# Generated by Django 3.0.5 on 2020-05-24 19:59

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200524_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment', old_name='user', new_name='Patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Time',
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'doctor'), (2, 'patient'), (3, 'HR'), (4, 'Receptionist')],
                default=2,
            ),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'Date',
                    models.DateField(default=datetime.date.today, verbose_name='Date'),
                ),
                ('Symptoms', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                (
                    'Doctor',
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='app.Doctor',
                    ),
                ),
                (
                    'Patient',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='app.Patient',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'Date',
                    models.DateField(default=datetime.date.today, verbose_name='Date'),
                ),
                ('remain', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('link', models.FileField(blank=True, upload_to='invoices')),
                (
                    'Patient',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='app.Patient',
                    ),
                ),
            ],
        ),
    ]
