# Generated by Django 3.0.5 on 2020-05-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200525_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment', old_name='Date', new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment', old_name='Doctor', new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment', old_name='Patient', new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointment', old_name='Time', new_name='time',
        ),
        migrations.RenameField(model_name='invoice', old_name='Date', new_name='date',),
        migrations.RenameField(
            model_name='invoice', old_name='Patient', new_name='patient',
        ),
        migrations.RenameField(
            model_name='prescription', old_name='Date', new_name='date',
        ),
        migrations.RenameField(
            model_name='prescription', old_name='Doctor', new_name='doctor',
        ),
        migrations.RenameField(
            model_name='prescription', old_name='Patient', new_name='patient',
        ),
    ]
