# Generated by Django 3.0.5 on 2020-05-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200525_0151'),
    ]

    operations = [
        migrations.RemoveField(model_name='patient', name='Email',),
        migrations.RemoveField(model_name='patient', name='bio',),
        migrations.RemoveField(model_name='patient', name='location',),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'A+'),
                    (2, 'A-'),
                    (3, 'B+'),
                    (4, 'B-'),
                    (5, 'AB+'),
                    (6, 'AB-'),
                    (7, 'O+'),
                    (8, 'O-'),
                ],
                default=7,
            ),
        ),
        migrations.AddField(
            model_name='patient',
            name='case_paper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='records',
            field=models.FileField(blank=True, upload_to='records'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Address',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Email',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Phone',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Speciality',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
