# Generated by Django 3.0.5 on 2020-05-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200525_0521'),
    ]

    operations = [
        migrations.DeleteModel(name='Receptionist',),
    ]
