# Generated by Django 3.0.5 on 2020-05-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_receptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Department',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Eye Care'),
                    (2, 'Skin Care'),
                    (3, 'Surgery'),
                    (4, 'Physical Therapy'),
                    (5, 'Dental'),
                ],
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Female'), (2, 'Male'), (3, 'Others')], default=3
            ),
        ),
    ]
