# Generated by Django 3.0.5 on 2020-05-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200525_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Phone',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
